name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar código fuente
      run: javac -d bin src/*.java

    - name: Compilar pruebas
      run: javac -cp ".:bin:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" -d bin test/*.java

    - name: Ejecutar pruebas unitarias
      run: java -cp ".:bin:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar" org.junit.runner.JUnitCore ProductoTest

